FROM nginx

RUN mkdir /usr/bin/codiba/Frontend

WORKDIR /usr/bin/codiba/Frontend

RUN mkdir ./build

COPY /home/azure/project-team5/Frontend/build ./build

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
