version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    # environment:
    #   - POSTGRES_DB=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
  app:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/usr/bin/codiba/Backend
    ports:
      - "8000:8000"
    depends_on:
      - db
