FROM python:3.9-alpine3.13

WORKDIR /usr/bin/codiba/Backend

COPY requirements.txt /usr/bin/codiba/Backend

RUN pip install -r requirements.txt

COPY . /usr/bin/codiba/Backend

CMD ["gunicorn", "-Db", "0.0.0.0:5000", "launcher.py"]