-- MySQL Script generated by MySQL Workbench
-- Sat Jun  5 23:47:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema codiba
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `codiba` ;

-- -----------------------------------------------------
-- Schema codiba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codiba` DEFAULT CHARACTER SET utf8mb4 ;
USE `codiba` ;

-- -----------------------------------------------------
-- Table `codiba`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codiba`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `codiba`.`codies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codiba`.`codies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NOT NULL,
  `gender` ENUM('m', 'w') NOT NULL DEFAULT 'm',
  `apparels` JSON NULL,
  `hits` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codiba`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codiba`.`likes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `codi_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_like_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_like_codi1_idx` (`codi_id` ASC) VISIBLE,
  CONSTRAINT `fk_like_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `codiba`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_codi1`
    FOREIGN KEY (`codi_id`)
    REFERENCES `codiba`.`codies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `codiba`.`user_has_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codiba`.`user_has_like` (
  `user_id` INT NOT NULL,
  `like_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `like_id`),
  INDEX `fk_user_has_like_like1_idx` (`like_id` ASC) VISIBLE,
  INDEX `fk_user_has_like_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_like_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `codiba`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_like_like1`
    FOREIGN KEY (`like_id`)
    REFERENCES `codiba`.`likes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codiba`.`directory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codiba`.`directory` (
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL DEFAULT 'default',
  `created_date` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`user_id`, `name`),
  INDEX `fk_directory_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_directory_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `codiba`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codiba`.`saved`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codiba`.`saved` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codi_id` INT NOT NULL,
  `directory_user_id` INT NOT NULL,
  `directory_name` VARCHAR(45) NOT NULL,
  `created_date` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_saved_codi1_idx` (`codi_id` ASC) VISIBLE,
  INDEX `fk_saved_directory1_idx` (`directory_user_id` ASC, `directory_name` ASC) VISIBLE,
  CONSTRAINT `fk_saved_codi1`
    FOREIGN KEY (`codi_id`)
    REFERENCES `codiba`.`codies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_saved_directory1`
    FOREIGN KEY (`directory_user_id` , `directory_name`)
    REFERENCES `codiba`.`directory` (`user_id` , `name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
