# Generated by Django 3.1.3 on 2021-05-27 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApperalCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "apperal_code",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=25)),
                ("detail_name", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Codies",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img_url", models.CharField(max_length=255)),
                ("origin", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Man"), ("W", "Woman")],
                        default="M",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "db_table": "codies",
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
            options={
                "db_table": "color",
            },
        ),
        migrations.CreateModel(
            name="Apperals",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=25)),
                ("detail_name", models.CharField(max_length=45)),
                ("color_name", models.CharField(max_length=25)),
                (
                    "apperal_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="codies.apperalcode",
                    ),
                ),
                (
                    "image_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="codies.codies"
                    ),
                ),
            ],
            options={
                "db_table": "apperals",
            },
        ),
        migrations.AddField(
            model_name="apperalcode",
            name="category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="codies.category"
            ),
        ),
        migrations.AddField(
            model_name="apperalcode",
            name="color_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="codies.color"
            ),
        ),
    ]
