# Generated by Django 3.1.3 on 2021-05-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apperals",
            name="category_name",
        ),
        migrations.RemoveField(
            model_name="apperals",
            name="color_name",
        ),
        migrations.RemoveField(
            model_name="apperals",
            name="detail_name",
        ),
        migrations.AddField(
            model_name="apperalcode",
            name="category_name",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="apperalcode",
            name="color_name",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="apperalcode",
            name="detail_name",
            field=models.CharField(max_length=45, null=True),
        ),
    ]
